import { Dimensions, StyleSheet } from "react-native";
import { COLORS } from "../../constants";

export const MENU_WIDTH = Dimensions.get("window").width * 0.78;
export const EDGE_ZONE = 24;

export const styles = StyleSheet.create({
    container: {
        ...StyleSheet.absoluteFillObject,
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0,0,0,0.55)",
    },
    edgeZone: {
        position: "absolute",
        top: 0,
        bottom: 0,
        left: 0,
        width: EDGE_ZONE,
    },
    drawer: {
        position: "absolute",
        top: 0,
        bottom: 0,
        left: 0,
        backgroundColor: COLORS.surface,
        borderRightWidth: 1,
        borderRightColor: COLORS.border,
        paddingHorizontal: 20,
        justifyContent: "space-between",
    },
    userSection: {
        alignItems: "flex-start",
        paddingVertical: 16,
        gap: 6,
    },
    avatar: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: COLORS.red,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 8,
    },
    avatarText: {
        fontFamily: "Bungee_400Regular",
        fontSize: 20,
        color: "#fff",
    },
    userName: {
        fontFamily: "Bungee_400Regular",
        fontSize: 18,
        color: COLORS.text,
        flex: 1,
    },
    userEmail: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 13,
        color: COLORS.textMuted,
    },
    nameRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        alignSelf: "stretch",
    },
    nameEditIcon: {
        fontSize: 14,
        color: COLORS.textMuted,
        flexShrink: 0,
    },
    nameInput: {
        backgroundColor: COLORS.surfaceAlt,
        borderRadius: 8,
        paddingVertical: 10,
        paddingHorizontal: 12,
        color: COLORS.text,
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 16,
        borderWidth: 1,
        borderColor: COLORS.border,
        width: "100%",
    },
    nameCharCount: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 11,
        color: COLORS.textMuted,
        alignSelf: "flex-end",
    },
    nameEditActions: {
        flexDirection: "row",
        gap: 8,
        width: "100%",
    },
    nameSaveBtn: {
        flex: 1,
        backgroundColor: COLORS.red,
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: "center",
    },
    nameSaveBtnText: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 13,
        color: "#fff",
    },
    nameCancelBtn: {
        flex: 1,
        backgroundColor: COLORS.surfaceAlt,
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: "center",
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    nameCancelBtnText: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 13,
        color: COLORS.textMuted,
    },
    nameBtnDisabled: {
        opacity: 0.5,
    },
    divider: {
        height: 1,
        backgroundColor: COLORS.border,
        marginVertical: 16,
    },
    sectionLabel: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 12,
        color: COLORS.textMuted,
        textTransform: "uppercase",
        letterSpacing: 1,
        marginBottom: 12,
    },
    houseItem: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        paddingVertical: 10,
        paddingHorizontal: 12,
        backgroundColor: COLORS.surfaceAlt,
        borderRadius: 10,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: "transparent",
    },
    houseItemActive: {
        borderColor: COLORS.red,
    },
    pendingHouseItem: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        paddingVertical: 10,
        paddingHorizontal: 12,
        backgroundColor: COLORS.surfaceAlt,
        borderRadius: 10,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: COLORS.border,
        opacity: 0.6,
    },
    houseActiveIndicator: {
        fontSize: 10,
        color: COLORS.red,
    },
    houseIcon: {
        width: 36,
        height: 36,
        borderRadius: 8,
        backgroundColor: COLORS.background,
        alignItems: "center",
        justifyContent: "center",
    },
    houseIconText: {
        fontSize: 18,
    },
    houseInfo: {
        flex: 1,
    },
    houseName: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 15,
        color: COLORS.text,
    },
    houseMeta: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 12,
        color: COLORS.textMuted,
        marginTop: 2,
    },
    emptyText: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 14,
        color: COLORS.textMuted,
        lineHeight: 20,
    },
    addHouseBtn: {
        marginTop: 12,
        paddingVertical: 13,
        paddingHorizontal: 14,
        borderRadius: 10,
        backgroundColor: COLORS.red,
        alignItems: "center",
    },
    addHouseBtnText: {
        fontFamily: "Bungee_400Regular",
        fontSize: 14,
        color: "#fff",
    },
    addHouseOptions: {
        marginTop: 6,
        gap: 6,
    },
    addHouseOption: {
        paddingVertical: 12,
        paddingHorizontal: 14,
        borderRadius: 10,
        backgroundColor: COLORS.surfaceAlt,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    addHouseOptionText: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 14,
        color: COLORS.text,
    },
    footer: {
        borderTopWidth: 1,
        borderTopColor: COLORS.border,
        paddingTop: 16,
    },
    tourBtn: {
        paddingVertical: 12,
        alignItems: "center",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: COLORS.border,
        marginBottom: 8,
    },
    tourBtnText: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 14,
        color: COLORS.text,
    },
    seedBtn: {
        paddingVertical: 12,
        alignItems: "center",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: COLORS.border,
        borderStyle: "dashed",
        marginBottom: 8,
    },
    seedBtnText: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 13,
        color: COLORS.textMuted,
    },
    logoutBtn: {
        paddingVertical: 12,
        alignItems: "center",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    logoutText: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 15,
        color: COLORS.danger,
    },
    deleteAccountBtn: {
        paddingVertical: 10,
        alignItems: "center",
    },
    deleteAccountText: {
        fontFamily: "NotoSansMono_400Regular",
        fontSize: 12,
        color: COLORS.textMuted,
        textDecorationLine: "underline",
    },
});
